# Form implementation generated from reading ui file 'dautupopup.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 650)
        Dialog.setStyleSheet("\n"
"    QDialog { background-color: white; border-radius: 20px; }\n"
"    QLabel#headerTitle { font-size: 18px; font-weight: bold; color: #001A41; }\n"
"    QFrame#calcBox { background-color: #F8FAFF; border-radius: 12px; border: 1px solid #E2E8F0; }\n"
"    QPushButton#btn_save { background-color: #002687; color: white; border-radius: 10px; font-weight: bold; padding: 15px; }\n"
"    QPushButton#btn_outline { background-color: white; border: 1px solid #E2E8F0; border-radius: 10px; padding: 15px; color: #002687; }\n"
"   ")
        self.vboxlayout = QtWidgets.QVBoxLayout(Dialog)
        self.vboxlayout.setContentsMargins(25, 25, 25, 25)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.headerTitle = QtWidgets.QLabel(parent=Dialog)
        self.headerTitle.setObjectName("headerTitle")
        self.hboxlayout.addWidget(self.headerTitle)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.btn_close = QtWidgets.QPushButton(parent=Dialog)
        self.btn_close.setObjectName("btn_close")
        self.hboxlayout.addWidget(self.btn_close)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.vboxlayout.addWidget(self.label)
        self.label1 = QtWidgets.QLabel(parent=Dialog)
        self.label1.setObjectName("label1")
        self.vboxlayout.addWidget(self.label1)
        self.label2 = QtWidgets.QLabel(parent=Dialog)
        self.label2.setObjectName("label2")
        self.vboxlayout.addWidget(self.label2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.vboxlayout.addItem(spacerItem1)
        self.calcBox = QtWidgets.QFrame(parent=Dialog)
        self.calcBox.setObjectName("calcBox")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.calcBox)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.label3 = QtWidgets.QLabel(parent=self.calcBox)
        self.label3.setObjectName("label3")
        self.vboxlayout1.addWidget(self.label3)
        self.lineedit = QtWidgets.QLineEdit(parent=self.calcBox)
        self.lineedit.setObjectName("lineedit")
        self.vboxlayout1.addWidget(self.lineedit)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.label4 = QtWidgets.QLabel(parent=self.calcBox)
        self.label4.setObjectName("label4")
        self.hboxlayout1.addWidget(self.label4)
        self.vboxlayout1.addLayout(self.hboxlayout1)
        self.vboxlayout.addWidget(self.calcBox)
        self.btn_save = QtWidgets.QPushButton(parent=Dialog)
        self.btn_save.setObjectName("btn_save")
        self.vboxlayout.addWidget(self.btn_save)
        self.btn_outline = QtWidgets.QPushButton(parent=Dialog)
        self.btn_outline.setObjectName("btn_outline")
        self.vboxlayout.addWidget(self.btn_outline)

        self.retranslateUi(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.headerTitle.setText(_translate("Dialog", "Vietcombank"))
        self.btn_close.setText(_translate("Dialog", "✕"))
        self.btn_close.setStyleSheet(_translate("Dialog", "border:none; font-size:16px;"))
        self.label.setText(_translate("Dialog", "★ Lãi suất cao nhất"))
        self.label.setStyleSheet(_translate("Dialog", "background: #DCFCE7; color: #059669; border-radius: 5px; padding: 5px;"))
        self.label1.setText(_translate("Dialog", "BẢNG LÃI SUẤT KỲ HẠN"))
        self.label1.setStyleSheet(_translate("Dialog", "font-size: 11px; font-weight: bold; color: #64748B; margin-top: 10px;"))
        self.label2.setText(_translate("Dialog", "12 tháng: 6.10%/năm"))
        self.label2.setStyleSheet(_translate("Dialog", "background: #F1F5FE; padding: 15px; font-weight: bold; border-radius: 8px;"))
        self.label3.setText(_translate("Dialog", "Số tiền gửi"))
        self.lineedit.setText(_translate("Dialog", "100.000.000 đ"))
        self.lineedit.setStyleSheet(_translate("Dialog", "background: white; border: 1px solid #ddd; padding: 10px; font-size: 16px; font-weight: bold;"))
        self.label4.setText(_translate("Dialog", "TIỀN LÃI: 6.100.000 đ"))
        self.label4.setStyleSheet(_translate("Dialog", "color: #059669; font-weight: bold;"))
        self.btn_save.setText(_translate("Dialog", "Mở sổ tiết kiệm ngay →"))
        self.btn_outline.setText(_translate("Dialog", "So sánh ngân hàng khác"))
