# Form implementation generated from reading ui file 'giaodich.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow_GiaoDich):
        MainWindow_GiaoDich.setObjectName("MainWindow_GiaoDich")
        MainWindow_GiaoDich.setGeometry(QtCore.QRect(0, 0, 1100, 850))
        MainWindow_GiaoDich.setStyleSheet("\n"
"    QMainWindow { background-color: #F8FAFC; }\n"
"    QFrame#frame_sidebar { background-color: #F1F5F9; border-right: 1px solid #E2E8F0; }\n"
"    /* Style cho các nút điều hướng sidebar */\n"
"    QPushButton[objectName^=\"btn_nav_\"] {\n"
"        text-align: left; padding: 12px 20px; border: none;\n"
"        border-radius: 8px; font-size: 14px; color: #64748B; margin: 2px 10px;\n"
"    }\n"
"    QPushButton[objectName^=\"btn_nav_\"]:hover { background-color: #E2E8F0; color: #1E293B; }\n"
"\n"
"    /* Nút đang được chọn (Giao dịch) */\n"
"    QPushButton#btn_nav_giaodich {\n"
"        background-color: #DBEAFE;\n"
"        color: #1E40AF;\n"
"        font-weight: bold;\n"
"    }\n"
"    /* Style cho bảng danh sách */\n"
"    QTableWidget#tbl_danhsach_giaodich { background-color: white; border: none; gridline-color: #F1F5F9; border-radius: 12px; }\n"
"    QHeaderView::section { background-color: #EEF2FD; padding: 10px; border: none; font-weight: bold; color: #64748B; }\n"
"   ")
        self.menubar_chinh = QtWidgets.QMenuBar(parent=MainWindow_GiaoDich)
        self.menubar_chinh.setGeometry(QtCore.QRect(0, 0, 1100, 22))
        self.menubar_chinh.setObjectName("menubar_chinh")
        self.menu_tep_tin = QtWidgets.QMenu(parent=self.menubar_chinh)
        self.menu_tep_tin.setObjectName("menu_tep_tin")
        self.menu_chinh_sua = QtWidgets.QMenu(parent=self.menubar_chinh)
        self.menu_chinh_sua.setObjectName("menu_chinh_sua")
        self.menu_tro_giup = QtWidgets.QMenu(parent=self.menubar_chinh)
        self.menu_tro_giup.setObjectName("menu_tro_giup")
        MainWindow_GiaoDich.setMenuBar(self.menubar_chinh)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow_GiaoDich)
        self.centralwidget.setObjectName("centralwidget")
        self.layout_tong_the = QtWidgets.QHBoxLayout(self.centralwidget)
        self.layout_tong_the.setContentsMargins(0, 0, 0, 0)
        self.layout_tong_the.setSpacing(0)
        self.layout_tong_the.setObjectName("layout_tong_the")
        self.frame_sidebar = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_sidebar.setMinimumSize(QtCore.QSize(240, 0))
        self.frame_sidebar.setObjectName("frame_sidebar")
        self.layout_sidebar_v = QtWidgets.QVBoxLayout(self.frame_sidebar)
        self.layout_sidebar_v.setSpacing(2)
        self.layout_sidebar_v.setObjectName("layout_sidebar_v")
        self.lbl_logo_app = QtWidgets.QLabel(parent=self.frame_sidebar)
        self.lbl_logo_app.setObjectName("lbl_logo_app")
        self.layout_sidebar_v.addWidget(self.lbl_logo_app)
        self.btn_nav_dashboard = QtWidgets.QPushButton(parent=self.frame_sidebar)
        self.btn_nav_dashboard.setObjectName("btn_nav_dashboard")
        self.layout_sidebar_v.addWidget(self.btn_nav_dashboard)
        self.btn_nav_giaodich = QtWidgets.QPushButton(parent=self.frame_sidebar)
        self.btn_nav_giaodich.setObjectName("btn_nav_giaodich")
        self.layout_sidebar_v.addWidget(self.btn_nav_giaodich)
        self.btn_nav_ngansach = QtWidgets.QPushButton(parent=self.frame_sidebar)
        self.btn_nav_ngansach.setObjectName("btn_nav_ngansach")
        self.layout_sidebar_v.addWidget(self.btn_nav_ngansach)
        self.btn_nav_dautu_tietkiem = QtWidgets.QPushButton(parent=self.frame_sidebar)
        self.btn_nav_dautu_tietkiem.setObjectName("btn_nav_dautu_tietkiem")
        self.layout_sidebar_v.addWidget(self.btn_nav_dautu_tietkiem)
        self.btn_nav_vayno = QtWidgets.QPushButton(parent=self.frame_sidebar)
        self.btn_nav_vayno.setObjectName("btn_nav_vayno")
        self.layout_sidebar_v.addWidget(self.btn_nav_vayno)
        self.btn_nav_baocao = QtWidgets.QPushButton(parent=self.frame_sidebar)
        self.btn_nav_baocao.setObjectName("btn_nav_baocao")
        self.layout_sidebar_v.addWidget(self.btn_nav_baocao)
        self.btn_nav_chatbot = QtWidgets.QPushButton(parent=self.frame_sidebar)
        self.btn_nav_chatbot.setObjectName("btn_nav_chatbot")
        self.layout_sidebar_v.addWidget(self.btn_nav_chatbot)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.layout_sidebar_v.addItem(spacerItem)
        self.btn_nav_caidat = QtWidgets.QPushButton(parent=self.frame_sidebar)
        self.btn_nav_caidat.setObjectName("btn_nav_caidat")
        self.layout_sidebar_v.addWidget(self.btn_nav_caidat)
        self.layout_tong_the.addWidget(self.frame_sidebar)
        self.widget_nội_dung_chính = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_nội_dung_chính.setObjectName("widget_nội_dung_chính")
        self.layout_noidung_v = QtWidgets.QVBoxLayout(self.widget_nội_dung_chính)
        self.layout_noidung_v.setContentsMargins(30, 30, 30, 30)
        self.layout_noidung_v.setSpacing(20)
        self.layout_noidung_v.setObjectName("layout_noidung_v")
        self.layout_noidung_header = QtWidgets.QHBoxLayout()
        self.layout_noidung_header.setObjectName("layout_noidung_header")
        self.lbl_tieude_trang = QtWidgets.QLabel(parent=self.widget_nội_dung_chính)
        self.lbl_tieude_trang.setObjectName("lbl_tieude_trang")
        self.layout_noidung_header.addWidget(self.lbl_tieude_trang)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layout_noidung_header.addItem(spacerItem1)
        self.lbl_user_info = QtWidgets.QLabel(parent=self.widget_nội_dung_chính)
        self.lbl_user_info.setObjectName("lbl_user_info")
        self.layout_noidung_header.addWidget(self.lbl_user_info)
        self.layout_noidung_v.addLayout(self.layout_noidung_header)
        self.layout_actions = QtWidgets.QHBoxLayout()
        self.layout_actions.setObjectName("layout_actions")
        self.btn_them_giaodich = QtWidgets.QPushButton(parent=self.widget_nội_dung_chính)
        self.btn_them_giaodich.setObjectName("btn_them_giaodich")
        self.layout_actions.addWidget(self.btn_them_giaodich)
        self.btn_nhap_excel = QtWidgets.QPushButton(parent=self.widget_nội_dung_chính)
        self.btn_nhap_excel.setObjectName("btn_nhap_excel")
        self.layout_actions.addWidget(self.btn_nhap_excel)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layout_actions.addItem(spacerItem2)
        self.txt_timkiem_giaodich = QtWidgets.QLineEdit(parent=self.widget_nội_dung_chính)
        self.txt_timkiem_giaodich.setMinimumSize(QtCore.QSize(280, 38))
        self.txt_timkiem_giaodich.setObjectName("txt_timkiem_giaodich")
        self.layout_actions.addWidget(self.txt_timkiem_giaodich)
        self.layout_noidung_v.addLayout(self.layout_actions)
        self.tbl_danhsach_giaodich = QtWidgets.QTableWidget(parent=self.widget_nội_dung_chính)
        self.tbl_danhsach_giaodich.setColumnCount(6)
        self.tbl_danhsach_giaodich.setRowCount(10)
        self.tbl_danhsach_giaodich.setObjectName("tbl_danhsach_giaodich")
        item = QtWidgets.QTableWidgetItem()
        self.tbl_danhsach_giaodich.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_danhsach_giaodich.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_danhsach_giaodich.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_danhsach_giaodich.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_danhsach_giaodich.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_danhsach_giaodich.setHorizontalHeaderItem(5, item)
        self.layout_noidung_v.addWidget(self.tbl_danhsach_giaodich)
        self.layout_tong_the.addWidget(self.widget_nội_dung_chính)
        MainWindow_GiaoDich.setCentralWidget(self.centralwidget)
        self.statusbar_chinh = QtWidgets.QStatusBar(parent=MainWindow_GiaoDich)
        self.statusbar_chinh.setObjectName("statusbar_chinh")
        MainWindow_GiaoDich.setStatusBar(self.statusbar_chinh)

        self.retranslateUi(MainWindow_GiaoDich)

    def retranslateUi(self, MainWindow_GiaoDich):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_GiaoDich.setWindowTitle(_translate("MainWindow", "Quản lý Giao dịch - Financial Architect"))
        self.menu_tep_tin.setTitle(_translate("MainWindow", "Tệp tin"))
        self.menu_chinh_sua.setTitle(_translate("MainWindow", "Chỉnh sửa"))
        self.menu_tro_giup.setTitle(_translate("MainWindow", "Trợ giúp"))
        self.lbl_logo_app.setText(_translate("MainWindow", "🏦 Tài chính"))
        self.lbl_logo_app.setStyleSheet(_translate("MainWindow", "font-size: 20px; font-weight: bold; color: #002D9C; margin: 20px 20px 30px 20px;"))
        self.btn_nav_dashboard.setText(_translate("MainWindow", "Dashboard"))
        self.btn_nav_giaodich.setText(_translate("MainWindow", "Giao dịch Thu-Chi"))
        self.btn_nav_ngansach.setText(_translate("MainWindow", "Ngân sách"))
        self.btn_nav_dautu_tietkiem.setText(_translate("MainWindow", "Đầu tư & Tiết kiệm"))
        self.btn_nav_vayno.setText(_translate("MainWindow", "Vay nợ"))
        self.btn_nav_baocao.setText(_translate("MainWindow", "Báo cáo"))
        self.btn_nav_chatbot.setText(_translate("MainWindow", "Chatbot"))
        self.btn_nav_caidat.setText(_translate("MainWindow", "Cài đặt hệ thống"))
        self.lbl_tieude_trang.setText(_translate("MainWindow", "Giao dịch Thu-Chi"))
        self.lbl_tieude_trang.setStyleSheet(_translate("MainWindow", "font-size: 22px; font-weight: bold;"))
        self.lbl_user_info.setText(_translate("MainWindow", "🔔  📤  👤"))
        self.lbl_user_info.setStyleSheet(_translate("MainWindow", "font-size: 16px;"))
        self.btn_them_giaodich.setText(_translate("MainWindow", "+ Thêm giao dịch"))
        self.btn_them_giaodich.setStyleSheet(_translate("MainWindow", "background-color: #002D9C; color: white; border-radius: 8px; padding: 10px 20px; font-weight: bold;"))
        self.btn_nhap_excel.setText(_translate("MainWindow", "📥 Import Excel"))
        self.btn_nhap_excel.setStyleSheet(_translate("MainWindow", "background-color: white; border: 1px solid #E2E8F0; border-radius: 8px; padding: 10px 15px;"))
        self.txt_timkiem_giaodich.setPlaceholderText(_translate("MainWindow", "Tìm kiếm giao dịch (Mô tả, Số tiền...)"))
        self.txt_timkiem_giaodich.setStyleSheet(_translate("MainWindow", "background-color: white; border: 1px solid #E2E8F0; border-radius: 10px; padding-left: 15px;"))
        item = self.tbl_danhsach_giaodich.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NGÀY"))
        item = self.tbl_danhsach_giaodich.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "MÔ TẢ"))
        item = self.tbl_danhsach_giaodich.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DANH MỤC"))
        item = self.tbl_danhsach_giaodich.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "LOẠI"))
        item = self.tbl_danhsach_giaodich.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "SỐ TIỀN"))
        item = self.tbl_danhsach_giaodich.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "THAO TÁC"))
