# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(1100, 750)
        self.horizontalLayout = QtWidgets.QHBoxLayout(LoginForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.mainCard = QtWidgets.QFrame(parent=LoginForm)
        self.mainCard.setMinimumSize(QtCore.QSize(1000, 650))
        self.mainCard.setMaximumSize(QtCore.QSize(1000, 650))
        self.mainCard.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.mainCard.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainCard.setObjectName("mainCard")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mainCard)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftPanel = QtWidgets.QWidget(parent=self.mainCard)
        self.leftPanel.setMinimumSize(QtCore.QSize(450, 0))
        self.leftPanel.setMaximumSize(QtCore.QSize(450, 16777215))
        self.leftPanel.setObjectName("leftPanel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftPanel)
        self.verticalLayout.setContentsMargins(50, 60, 50, 60)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logoLabel = QtWidgets.QLabel(parent=self.leftPanel)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.logoLabel.setFont(font)
        self.logoLabel.setObjectName("logoLabel")
        self.verticalLayout.addWidget(self.logoLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.titleLabel = QtWidgets.QLabel(parent=self.leftPanel)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setWordWrap(True)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.descLabel = QtWidgets.QLabel(parent=self.leftPanel)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.descLabel.setFont(font)
        self.descLabel.setWordWrap(True)
        self.descLabel.setObjectName("descLabel")
        self.verticalLayout.addWidget(self.descLabel)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2.addWidget(self.leftPanel)
        self.rightPanel = QtWidgets.QWidget(parent=self.mainCard)
        self.rightPanel.setObjectName("rightPanel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.rightPanel)
        self.verticalLayout_2.setContentsMargins(70, 60, 70, 40)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.welcomeLabel = QtWidgets.QLabel(parent=self.rightPanel)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.welcomeLabel.setFont(font)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.verticalLayout_2.addWidget(self.welcomeLabel)
        self.subWelcomeLabel = QtWidgets.QLabel(parent=self.rightPanel)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.subWelcomeLabel.setFont(font)
        self.subWelcomeLabel.setObjectName("subWelcomeLabel")
        self.verticalLayout_2.addWidget(self.subWelcomeLabel)
        spacerItem4 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.emailLabel = QtWidgets.QLabel(parent=self.rightPanel)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.emailLabel.setFont(font)
        self.emailLabel.setObjectName("emailLabel")
        self.verticalLayout_2.addWidget(self.emailLabel)
        self.emailInput = QtWidgets.QLineEdit(parent=self.rightPanel)
        self.emailInput.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.emailInput.setFont(font)
        self.emailInput.setObjectName("emailInput")
        self.verticalLayout_2.addWidget(self.emailInput)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.passwordLabel = QtWidgets.QLabel(parent=self.rightPanel)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setObjectName("passwordLabel")
        self.horizontalLayout_3.addWidget(self.passwordLabel)
        self.forgotPwdLabel = QtWidgets.QLabel(parent=self.rightPanel)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.forgotPwdLabel.setFont(font)
        self.forgotPwdLabel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.forgotPwdLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.forgotPwdLabel.setObjectName("forgotPwdLabel")
        self.horizontalLayout_3.addWidget(self.forgotPwdLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.passwordInput = QtWidgets.QLineEdit(parent=self.rightPanel)
        self.passwordInput.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.passwordInput.setFont(font)
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.verticalLayout_2.addWidget(self.passwordInput)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem6)
        self.loginBtn = QtWidgets.QPushButton(parent=self.rightPanel)
        self.loginBtn.setMinimumSize(QtCore.QSize(0, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.loginBtn.setFont(font)
        self.loginBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.loginBtn.setObjectName("loginBtn")
        self.verticalLayout_2.addWidget(self.loginBtn)
        spacerItem7 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.line_1 = QtWidgets.QFrame(parent=self.rightPanel)
        self.line_1.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_1.setObjectName("line_1")
        self.horizontalLayout_4.addWidget(self.line_1)
        self.orLabel = QtWidgets.QLabel(parent=self.rightPanel)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.orLabel.setFont(font)
        self.orLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.orLabel.setObjectName("orLabel")
        self.horizontalLayout_4.addWidget(self.orLabel)
        self.line_2 = QtWidgets.QFrame(parent=self.rightPanel)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_4.addWidget(self.line_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem8 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem8)
        self.googleBtn = QtWidgets.QPushButton(parent=self.rightPanel)
        self.googleBtn.setMinimumSize(QtCore.QSize(0, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.googleBtn.setFont(font)
        self.googleBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.googleBtn.setObjectName("googleBtn")
        self.verticalLayout_2.addWidget(self.googleBtn)
        spacerItem9 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem9)
        self.signupLabel = QtWidgets.QLabel(parent=self.rightPanel)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.signupLabel.setFont(font)
        self.signupLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.signupLabel.setOpenExternalLinks(False)
        self.signupLabel.setObjectName("signupLabel")
        self.verticalLayout_2.addWidget(self.signupLabel)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem10)
        self.footerLayout = QtWidgets.QHBoxLayout()
        self.footerLayout.setObjectName("footerLayout")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.footerLayout.addItem(spacerItem11)
        self.helpLabel = QtWidgets.QLabel(parent=self.rightPanel)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.helpLabel.setFont(font)
        self.helpLabel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.helpLabel.setObjectName("helpLabel")
        self.footerLayout.addWidget(self.helpLabel)
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.footerLayout.addItem(spacerItem12)
        self.privacyLabel = QtWidgets.QLabel(parent=self.rightPanel)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.privacyLabel.setFont(font)
        self.privacyLabel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.privacyLabel.setObjectName("privacyLabel")
        self.footerLayout.addWidget(self.privacyLabel)
        spacerItem13 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.footerLayout.addItem(spacerItem13)
        self.regionLabel = QtWidgets.QLabel(parent=self.rightPanel)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.regionLabel.setFont(font)
        self.regionLabel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.regionLabel.setObjectName("regionLabel")
        self.footerLayout.addWidget(self.regionLabel)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.footerLayout.addItem(spacerItem14)
        self.verticalLayout_2.addLayout(self.footerLayout)
        self.horizontalLayout_2.addWidget(self.rightPanel)
        self.horizontalLayout.addWidget(self.mainCard)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem15)

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "Đăng nhập - Financial Architect"))
        LoginForm.setStyleSheet(_translate("LoginForm", "QWidget#LoginForm {\n"
"    background-color: #f0f2f5;\n"
"}"))
        self.mainCard.setStyleSheet(_translate("LoginForm", "QFrame#mainCard {\n"
"    background-color: transparent;\n"
"}"))
        self.leftPanel.setStyleSheet(_translate("LoginForm", "QWidget#leftPanel {\n"
"    background-color: #123485;\n"
"    border-top-left-radius: 12px;\n"
"    border-bottom-left-radius: 12px;\n"
"}"))
        self.logoLabel.setStyleSheet(_translate("LoginForm", "color: white;"))
        self.logoLabel.setText(_translate("LoginForm", "🏦 Financial Architect"))
        self.titleLabel.setStyleSheet(_translate("LoginForm", "color: white;"))
        self.titleLabel.setText(_translate("LoginForm", "Làm chủ tài chính\n"
"của bạn."))
        self.descLabel.setStyleSheet(_translate("LoginForm", "color: #d1d5db;"))
        self.descLabel.setText(_translate("LoginForm", "Hệ thống quản lý tài chính thông minh giúp bạn hoạch định tương lai vững chắc và đạt được sự tự do tài chính."))
        self.rightPanel.setStyleSheet(_translate("LoginForm", "QWidget#rightPanel {\n"
"    background-color: white;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-right-radius: 12px;\n"
"    border: 1px solid #e5e7eb;\n"
"    border-left: none;\n"
"}"))
        self.welcomeLabel.setStyleSheet(_translate("LoginForm", "color: #111827;"))
        self.welcomeLabel.setText(_translate("LoginForm", "Chào mừng trở lại"))
        self.subWelcomeLabel.setStyleSheet(_translate("LoginForm", "color: #4b5563;\n"
"margin-top: 5px;"))
        self.subWelcomeLabel.setText(_translate("LoginForm", "Vui lòng đăng nhập để quản lý tài khoản của bạn."))
        self.emailLabel.setStyleSheet(_translate("LoginForm", "color: #374151;"))
        self.emailLabel.setText(_translate("LoginForm", "Email"))
        self.emailInput.setStyleSheet(_translate("LoginForm", "QLineEdit {\n"
"    background-color: #f3f6fc;\n"
"    border: 1px solid transparent;\n"
"    border-radius: 6px;\n"
"    padding: 10px;\n"
"    color: #111827;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid #123485;\n"
"}"))
        self.emailInput.setPlaceholderText(_translate("LoginForm", "✉  example@email.com"))
        self.passwordLabel.setStyleSheet(_translate("LoginForm", "color: #374151;"))
        self.passwordLabel.setText(_translate("LoginForm", "Mật khẩu"))
        self.forgotPwdLabel.setStyleSheet(_translate("LoginForm", "color: #123485;"))
        self.forgotPwdLabel.setText(_translate("LoginForm", "Quên mật khẩu?"))
        self.passwordInput.setStyleSheet(_translate("LoginForm", "QLineEdit {\n"
"    background-color: #f3f6fc;\n"
"    border: 1px solid transparent;\n"
"    border-radius: 6px;\n"
"    padding: 10px;\n"
"    color: #111827;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid #123485;\n"
"}"))
        self.passwordInput.setPlaceholderText(_translate("LoginForm", "🔒  ••••••••"))
        self.loginBtn.setStyleSheet(_translate("LoginForm", "QPushButton {\n"
"    background-color: #123485;\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0e276b;\n"
"}"))
        self.loginBtn.setText(_translate("LoginForm", "Đăng nhập"))
        self.line_1.setStyleSheet(_translate("LoginForm", "color: #e5e7eb;"))
        self.orLabel.setStyleSheet(_translate("LoginForm", "color: #6b7280;"))
        self.orLabel.setText(_translate("LoginForm", "HOẶC ĐĂNG NHẬP VỚI"))
        self.line_2.setStyleSheet(_translate("LoginForm", "color: #e5e7eb;"))
        self.googleBtn.setStyleSheet(_translate("LoginForm", "QPushButton {\n"
"    background-color: white;\n"
"    color: #374151;\n"
"    border: 1px solid #d1d5db;\n"
"    border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #f9fafb;\n"
"}"))
        self.googleBtn.setText(_translate("LoginForm", "G   Google"))
        self.signupLabel.setStyleSheet(_translate("LoginForm", "color: #4b5563;"))
        self.signupLabel.setText(_translate("LoginForm", "<html><head/><body><p>Chưa có tài khoản? <span style=\" font-weight:700; color:#123485;\">Đăng ký tài khoản mới</span></p></body></html>"))
        self.helpLabel.setStyleSheet(_translate("LoginForm", "color: #6b7280;"))
        self.helpLabel.setText(_translate("LoginForm", "Trợ giúp"))
        self.privacyLabel.setStyleSheet(_translate("LoginForm", "color: #6b7280;"))
        self.privacyLabel.setText(_translate("LoginForm", "Quyền riêng tư"))
        self.regionLabel.setStyleSheet(_translate("LoginForm", "color: #6b7280;"))
        self.regionLabel.setText(_translate("LoginForm", "Việt Nam (VN)"))
